---

- name: Install fastfetch using paru
  ansible.builtin.command: paru -S --noconfirm fastfetch
  register: install_fastfetch
  become: false

- name: Create fastfetch configuration directory
  ansible.builtin.file:
    path: "~/.config/fastfetch"
    state: directory
    mode: '0755'
  become: false

- name: Copy fastfetch configuration
  ansible.builtin.copy:
    src: "{{ role_path }}/files/fastfetch.jsonc"
    dest: "~/.config/fastfetch/config.jsonc"
    mode: '0644'
  become: false
