# Default colors
[colors.primary]
background = '#0f0d0a'
#background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[window]
opacity = 0.95
padding.x = 10
padding.y = 10

[font]
normal.family = "BlexMono Nerd Font"
bold.family = "BlexMono Nerd Font"
italic.family = "BlexMono Nerd Font"
bold_italic.family = "BlexMono Nerd Font"

size = 12
