#!/bin/bash

# Flags to mark the completion of each section.
INITIAL_SETUP=1
SYSTEM_RESET=1
ESSENTIALS_COMPLETED=0
INTERFACE_COMPLETED=0
PRIVACY_COMPLETED=1
DEVELOPMENT_COMPLETED=0
DESKTOP_COMPLETED=0
SECURITY_COMPLETED=1
