set -g prefix C-a
set -g aggressive-resize on
set -g bell-action none

set-option -g history-limit 25000
set -g mouse on

# For neovim
set -sg escape-time 10
set-option -g focus-events on

# Keybindings
bind ! split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind n new-window
bind x kill-pane
bind k kill-window
bind q kill-session
bind r source-file ~/.tmux.conf
bind t select-layout tiled

# Status Bar
set -g status-position top
set -g status-bg colour234
set -g status-fg colour137
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

# Rename panes to current working directory
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# Term colors, these are the correct ones according to neovim checkhealth
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# Set zsh as default shell
set-option -g default-shell /bin/zsh
